In [2]:
import nevergrad as ng
from obj_funcs_lib import *
import numpy as np
import time

def optimize_with_bo(start_point, objective, bo_budget=100):
    """
    Optimizes a given `objective` function starting from `start_point`
    using Bayesian Optimization from nevergrad.
    """
    bo_optimizer_cls = ng.optimizers.registry['BO']
    parametrization = ng.p.Array(init=start_point)
    bo_optimizer = bo_optimizer_cls(parametrization=parametrization, budget=bo_budget)
    bo_result = bo_optimizer.minimize(lambda x: objective(x))
    current_pos = np.array(bo_result.value)
    current_obj_value = objective(current_pos)
    print(current_pos)
    print(current_obj_value)
    return current_pos, current_obj_value

results = {}
for name, obj_func in OBJ_FUNCS.items():
    print(f"Optimizing {name} with BO...")
    start_time = time.time()
    result = optimize_with_bo(
        start_point=[200]*3,
        objective=obj_func,
    )
    elapsed = time.time() - start_time
    print(f"Time taken for {name}: {elapsed:.2f} seconds")
    results[name] = result
    print('='*20)


Optimizing sphere with BO...


c:\Users\Benny\anaconda3\Lib\site-packages\nevergrad\optimization\base.py:149: LossTooLargeWarning: Clipping very high value 5.3341875762270116e+32 in tell (rescale the cost function?).
  warnings.warn(msg, e)


[199.81324541 -35.70508388 200.95434152]
81582.83343211241
Time taken for sphere: 5.52 seconds
Optimizing rosenbrock with BO...
[166.17596532 197.58631589 201.93118328]
[2.2601081e+11]
Time taken for rosenbrock: 5.88 seconds
Optimizing rastrigin with BO...


c:\Users\Benny\anaconda3\Lib\site-packages\nevergrad\optimization\base.py:149: LossTooLargeWarning: Clipping very high value 5.3341875762270116e+32 in tell (rescale the cost function?).
  warnings.warn(msg, e)


[199.84811236 129.65708777 198.46453591]
96177.88357074425
Time taken for rastrigin: 7.31 seconds
Optimizing ackley with BO...
[201.0145278  198.98423704 198.98825961]
[20.0106559]
Time taken for ackley: 5.00 seconds
Optimizing griewank with BO...
[  3.32125745 167.59981655 198.34929546]
[17.95635213]
Time taken for griewank: 10.21 seconds
